// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_IHnFmw4juBC3PiucM8-1aWwHhZFuBUg',
    appId: '1:319785910228:web:5e4657505a35d25c0de041',
    messagingSenderId: '319785910228',
    projectId: 'neighborhandydb',
    authDomain: 'neighborhandydb.firebaseapp.com',
    storageBucket: 'neighborhandydb.firebasestorage.app',
    measurementId: 'G-KEQMHD77BS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAubwyKiVfe_NXF9hrJSLQk1k4Fk4gwuk',
    appId: '1:319785910228:android:fa992e5f4caff6160de041',
    messagingSenderId: '319785910228',
    projectId: 'neighborhandydb',
    storageBucket: 'neighborhandydb.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsannUsmm40VG0h8REVcO5NZEvqzrLvKw',
    appId: '1:309352549072:ios:582c5009cd60678a9becd5',
    messagingSenderId: '309352549072',
    projectId: 'neighborhandy-4dc83',
    storageBucket: 'neighborhandy-4dc83.firebasestorage.app',
    iosBundleId: 'com.example.neighbohandy',
  );
}
